stages:
  - test
  - build
  - deploy

default:
  image: node:12-alpine

# -------
#  JOBS
# -------

lint:
  stage: test
  script:
    - npm ci
    - npm run lint

build:
  stage: build
  artifacts:
    paths:
      - dist/
    name: "$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG-$CI_JOB_ID"
  script:
    - npm ci
    - npm run build

publish:
  stage: deploy
  dependencies:
    - build
  only:
    - tags
  script:
    - echo "//${NPM_REGISTRY_DOMAIN}/:_authToken=${NPM_AUTH_TOKEN}" >> .npmrc
    - npm publish --access public
